
name: prebuild-data

on:
  # push:
  #   branches:
  #     - master
  # pull_request:
  #   branches:
  #     - master
  workflow_dispatch:

jobs:
  prebuild-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create branch
        run: |
          git checkout -b generic/data

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install
        run: npm install
          
      - name: Configure git user
        run: |
          git config --local user.email "noreply@arnaud.tech"
          git config --local user.name "Github Actions"

      - name: Push
        run: |
          git add node_modules package-lock.json
          git commit -m "Update libs"
          git push -f origin generic/data
